# Site
repository: ecart18/ecart18.github.io
# favicon: images/favicon.ico

# Personal info
name: Tao Hu
title: Tsinghua University - Ph.D Candidate
email: ecart.hut@gmail.com
website: linkedin.com/in/tao-h-0b7749169

# Social links
# twitter_username: no**name
# github_username: ecart18
# dribbble_username: no**name
# facebook_username: no**name
# flickr_username: no**name
# instagram_username: no**name
# linkedin_username: tao-h-0b7749169
# pinterest_username: no**name
# youtube_username: no**name
# googleplus_username: no**name

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Tao Hu and I'm a Ph.D candidate of Department of Automation, Tsinghua University, as well as an researcher in the field of deep learning, machine learning and computer vision. I also have experience in statistic analysis, and have the knowledge of bioinformatics and data mining. I have worked as an algorithm intern at Horizon Robotics for 18 months, and have gained teamwork ability and professional skills in computer vision, especially in object tracking/segmentation/detection and person ReID.

  I am most skilled in: <mark>Deep Learning</mark> <mark>Machine Learning</mark> <mark>Computer vision</mark> <mark>Eating Spicy Food</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in machine learning and computer vison, some of my other interests and hobbies are:
   - One Piece
   - Cyber Cats Petting
   - LeBron James's Fan

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
